require 'hoe'
require './lib/csvjson/version.rb'

Hoe.spec 'csvjson' do

  self.version = CsvJson::VERSION

  self.summary = "csvjson - read tabular data in the CSV <3 JSON format, that is, comma-separated values CSV (line-by-line) records with javascript object notation (JSON) encoding rules"
  self.description = summary

  self.urls    = ['https://github.com/csvreader/csvjson']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
